# This is a basic workflow to help you get started with Actions

name: CD/CI pipeline

on:
  workflow_dispatch:

env:
  BUCKET: a-test-bucket-19
  TFSTATE_FILE: vpc.tfstate 
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    # - name: Terraform Format
    #     id: fmt
    #     run: terraform fmt -check

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ID_KEY}}
        aws-region: ap-northeast-1

      - name: Terraform Init
        run: |
          cd example

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: cd example
        terraform plan -no-color

      # On push to master, build or change infrastructure according to Terraform configuration files
    - name: Terraform Apply
      #if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: cd example
          terraform apply -auto-approve
